/*****************************************************************************
* Copyright 2015-2026 Alexander Barthel alex@littlenavmap.org
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*****************************************************************************/

#include "countryupdater.h"
#include "fs/util/fsutil.h"
#include "sql/sqldatabase.h"
#include "sql/sqlquery.h"
#include "timezone/timezonemanager.h"

#include <QHash>
#include <QStringList>

namespace atools {
namespace fs {
namespace db {

// All possible country errors collected from X-Plane 11 and 12 community airports
// Key is upper case
const QHash<QString, QString> CountryUpdater::countries({
        {QStringLiteral("- NEW CALEDONIA"), QStringLiteral("New Caledonia")},
        {QStringLiteral("A CORUNA"), QStringLiteral("Spain")},
        {QStringLiteral("AGO"), QStringLiteral()},
        {QStringLiteral("ARG"), QStringLiteral()},
        {QStringLiteral("ARM"), QStringLiteral()},
        {QStringLiteral("ATF"), QStringLiteral()},
        {QStringLiteral("ATG"), QStringLiteral()},
        {QStringLiteral("AUS"), QStringLiteral()},
        {QStringLiteral("AUT"), QStringLiteral()},
        {QStringLiteral("AZE"), QStringLiteral()},
        {QStringLiteral("ARIZONA"), QStringLiteral("United States")},
        {QStringLiteral("AUSTRAIA"), QStringLiteral("Australia")},
        {QStringLiteral("BEL"), QStringLiteral()},
        {QStringLiteral("BFA"), QStringLiteral()},
        {QStringLiteral("BG"), QStringLiteral("Bulgaria")},
        {QStringLiteral("BGD"), QStringLiteral()},
        {QStringLiteral("BGR"), QStringLiteral()},
        {QStringLiteral("BHR"), QStringLiteral()},
        {QStringLiteral("BHS"), QStringLiteral()},
        {QStringLiteral("BIH"), QStringLiteral()},
        {QStringLiteral("BLR"), QStringLiteral()},
        {QStringLiteral("BLZ"), QStringLiteral()},
        {QStringLiteral("BOL"), QStringLiteral()},
        {QStringLiteral("BRA"), QStringLiteral()},
        {QStringLiteral("BOSNIA"), QStringLiteral("Bosnia and Herzegovina")},
        {QStringLiteral("BRASIL"), QStringLiteral("Brazil")},
        {QStringLiteral("BURKINA FASO7"), QStringLiteral("Burkina Faso")},
        {QStringLiteral("CAN"), QStringLiteral()},
        {QStringLiteral("CHE"), QStringLiteral()},
        {QStringLiteral("CHL"), QStringLiteral()},
        {QStringLiteral("CHN"), QStringLiteral()},
        {QStringLiteral("COD"), QStringLiteral()},
        {QStringLiteral("COG"), QStringLiteral()},
        {QStringLiteral("COL"), QStringLiteral()},
        {QStringLiteral("CRI"), QStringLiteral()},
        {QStringLiteral("CUB"), QStringLiteral()},
        {QStringLiteral("CYP"), QStringLiteral()},
        {QStringLiteral("COLUMBIA"), QStringLiteral("Colombia")},
        {QStringLiteral("COMMONWEALTH OF THE BAHAMAS"), QStringLiteral("Bahamas")},
        {QStringLiteral("CURAÇAO"), QStringLiteral("Curacao")},
        {QStringLiteral("DEU"), QStringLiteral("Germany")},
        {QStringLiteral("DJI"), QStringLiteral()},
        {QStringLiteral("DOM"), QStringLiteral()},
        {QStringLiteral("DZA"), QStringLiteral()},
        {QStringLiteral("ECU"), QStringLiteral()},
        {QStringLiteral("EGY"), QStringLiteral()},
        {QStringLiteral("ESP"), QStringLiteral()},
        {QStringLiteral("EST"), QStringLiteral()},
        {QStringLiteral("ENGLAND"), QStringLiteral("United Kingdom")},
        {QStringLiteral("FIN"), QStringLiteral()},
        {QStringLiteral("FRA"), QStringLiteral()},
        {QStringLiteral("FRANCES"), QStringLiteral("France")},
        {QStringLiteral("GAB"), QStringLiteral()},
        {QStringLiteral("GBR"), QStringLiteral()},
        {QStringLiteral("GEO"), QStringLiteral()},
        {QStringLiteral("GNQ"), QStringLiteral()},
        {QStringLiteral("GRC"), QStringLiteral()},
        {QStringLiteral("GTM"), QStringLiteral()},
        {QStringLiteral("GERMANY (CIVIL)"), QStringLiteral("Germany")},
        {QStringLiteral("HONG KONG SA REGION"), QStringLiteral("Hong Kong")},
        {QStringLiteral("IDN"), QStringLiteral()},
        {QStringLiteral("IN"), QStringLiteral("India")},
        {QStringLiteral("IND"), QStringLiteral()},
        {QStringLiteral("IRL"), QStringLiteral()},
        {QStringLiteral("IRN"), QStringLiteral()},
        {QStringLiteral("ISR"), QStringLiteral()},
        {QStringLiteral("ITA"), QStringLiteral()},
        {QStringLiteral("JPN"), QStringLiteral()},
        {QStringLiteral("K1"), QStringLiteral("United States")},
        {QStringLiteral("KAZ"), QStringLiteral()},
        {QStringLiteral("KEN"), QStringLiteral()},
        {QStringLiteral("KGZ"), QStringLiteral()},
        {QStringLiteral("KHM"), QStringLiteral()},
        {QStringLiteral("KOR"), QStringLiteral()},
        {QStringLiteral("KWT"), QStringLiteral()},
        {QStringLiteral("LAO"), QStringLiteral()},
        {QStringLiteral("LBY"), QStringLiteral()},
        {QStringLiteral("LKA"), QStringLiteral()},
        {QStringLiteral("LUX"), QStringLiteral()},
        {QStringLiteral("LVA"), QStringLiteral()},
        {QStringLiteral("MDV"), QStringLiteral()},
        {QStringLiteral("MEX"), QStringLiteral()},
        {QStringLiteral("MHL"), QStringLiteral()},
        {QStringLiteral("MMR"), QStringLiteral()},
        {QStringLiteral("MNG"), QStringLiteral()},
        {QStringLiteral("MTQ"), QStringLiteral()},
        {QStringLiteral("MWI"), QStringLiteral()},
        {QStringLiteral("MYS"), QStringLiteral()},
        {QStringLiteral("NAM"), QStringLiteral()},
        {QStringLiteral("NCL"), QStringLiteral()},
        {QStringLiteral("NIC"), QStringLiteral()},
        {QStringLiteral("NOR"), QStringLiteral()},
        {QStringLiteral("NZL"), QStringLiteral()},
        {QStringLiteral("NAMIBIA."), QStringLiteral("Namibia")},
        {QStringLiteral("NEW-ZEALAND"), QStringLiteral("New Zealand")},
        {QStringLiteral("OMN"), QStringLiteral()},
        {QStringLiteral("PAK"), QStringLiteral()},
        {QStringLiteral("PAN"), QStringLiteral()},
        {QStringLiteral("PER"), QStringLiteral()},
        {QStringLiteral("PHL"), QStringLiteral()},
        {QStringLiteral("PNG"), QStringLiteral()},
        {QStringLiteral("POL"), QStringLiteral()},
        {QStringLiteral("PRI"), QStringLiteral()},
        {QStringLiteral("PRK"), QStringLiteral()},
        {QStringLiteral("PRT"), QStringLiteral()},
        {QStringLiteral("PRY"), QStringLiteral()},
        {QStringLiteral("PYF"), QStringLiteral()},
        {QStringLiteral("PAPA NEW GUINEA"), QStringLiteral("Papua New Guinea")},
        {QStringLiteral("PAPUA NREW GUINEA"), QStringLiteral("Papua New Guinea")},
        {QStringLiteral("PAPUA"), QStringLiteral("Papua New Guinea")},
        {QStringLiteral("PARAGUY"), QStringLiteral("Paraguay")},
        {QStringLiteral("PEOPLES REPUBLIC OF CHINA"), QStringLiteral("China")},
        {QStringLiteral("PERÚ"), QStringLiteral("Peru")},
        {QStringLiteral("PUERTO RICOL"), QStringLiteral("Puerto Rico")},
        {QStringLiteral("QAT"), QStringLiteral()},
        {QStringLiteral("ROU"), QStringLiteral()},
        {QStringLiteral("RP"), QStringLiteral("Philippines")},
        {QStringLiteral("RUS RF"), QStringLiteral("Russia")},
        {QStringLiteral("RUS"), QStringLiteral("Russia")},
        {QStringLiteral("REPUBLIC OF CHINA"), QStringLiteral("China")},
        {QStringLiteral("RUSSIAN FEDERATION"), QStringLiteral("Russia")},
        {QStringLiteral("RUSSIN FEDERATION"), QStringLiteral("Russia")},
        {QStringLiteral("SAU"), QStringLiteral()},
        {QStringLiteral("SEN"), QStringLiteral()},
        {QStringLiteral("SLB"), QStringLiteral()},
        {QStringLiteral("SLV"), QStringLiteral()},
        {QStringLiteral("SMR"), QStringLiteral()},
        {QStringLiteral("SRB"), QStringLiteral()},
        {QStringLiteral("STP"), QStringLiteral()},
        {QStringLiteral("SUR"), QStringLiteral()},
        {QStringLiteral("SVK"), QStringLiteral()},
        {QStringLiteral("SVN"), QStringLiteral()},
        {QStringLiteral("SWE"), QStringLiteral()},
        {QStringLiteral("SWZ"), QStringLiteral()},
        {QStringLiteral("SLOVENSKO"), QStringLiteral("Slovakia")},
        {QStringLiteral("SOUTH SFRICA"), QStringLiteral("South Africa")},
        {QStringLiteral("SOUTH-AFRICA"), QStringLiteral("South Africa")},
        {QStringLiteral("SVALBARD AND JAN MAYEN"), QStringLiteral("Svalbard and Jan Mayen")},
        {QStringLiteral("SWISS"), QStringLiteral("Switzerland")},
        {QStringLiteral("THA"), QStringLiteral()},
        {QStringLiteral("TKM"), QStringLiteral()},
        {QStringLiteral("TUR"), QStringLiteral()},
        {QStringLiteral("TURKMENISTAN"), QStringLiteral("Turkmenistan")},
        {QStringLiteral("TZA"), QStringLiteral()},
        {QStringLiteral("TURKIYE"), QStringLiteral("Turkey")},
        {QStringLiteral("U,S,"), QStringLiteral("United States")},
        {QStringLiteral("U.S"), QStringLiteral("United States")},
        {QStringLiteral("U.S. VIRGIN ISLANDS"), QStringLiteral()},
        {QStringLiteral("U.S.A."), QStringLiteral("United States")},
        {QStringLiteral("UGA"), QStringLiteral()},
        {QStringLiteral("UKR"), QStringLiteral()},
        {QStringLiteral("UMI"), QStringLiteral()},
        {QStringLiteral("URY"), QStringLiteral()},
        {QStringLiteral("US STATES  CONTIGUOUS"), QStringLiteral("United States")},
        {QStringLiteral("US STATES | CONTIGUOUS"), QStringLiteral("United States")},
        {QStringLiteral("USA UNITED STATES"), QStringLiteral("United States")},
        {QStringLiteral("USA"), QStringLiteral("United States")},
        {QStringLiteral("UZB"), QStringLiteral()},
        {QStringLiteral("UK"), QStringLiteral("United Kingdom")},
        {QStringLiteral("UNIED KINGDOM"), QStringLiteral("United Kingdom")},
        {QStringLiteral("UNITED SATES"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATE"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATES (ALASKA)"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATES (CONTIGUOUS)"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATES MINOR OUTLYING ISLANDS"), QStringLiteral("United States Outlying Islands")},
        {QStringLiteral("UNITED STATES OF AMERICA"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATES OF ANERICA"), QStringLiteral("United States")},
        {QStringLiteral("UNITED STATESV"), QStringLiteral("United States")},
        {QStringLiteral("UNITEDSTATES"), QStringLiteral("United States")},
        {QStringLiteral("UNITES STATES"), QStringLiteral("United States")},
        {QStringLiteral("VEN"), QStringLiteral()},
        {QStringLiteral("VIR"), QStringLiteral()},
        {QStringLiteral("VNM"), QStringLiteral()},
        {QStringLiteral("VIET NAM"), QStringLiteral("Vietnam")},
        {QStringLiteral("ZAF"), QStringLiteral()},
        {QStringLiteral("ZW"), QStringLiteral("Zimbabwe")}
      });

// https://www.iban.com/country-codes
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
const QHash<QString, QString> CountryUpdater::country3To2({
        {QStringLiteral("ABW"), QStringLiteral("AW")},
        {QStringLiteral("AFG"), QStringLiteral("AF")},
        {QStringLiteral("AGO"), QStringLiteral("AO")},
        {QStringLiteral("AIA"), QStringLiteral("AI")},
        {QStringLiteral("ALA"), QStringLiteral("AX")},
        {QStringLiteral("ALB"), QStringLiteral("AL")},
        {QStringLiteral("AND"), QStringLiteral("AD")},
        {QStringLiteral("ARE"), QStringLiteral("AE")},
        {QStringLiteral("ARG"), QStringLiteral("AR")},
        {QStringLiteral("ARM"), QStringLiteral("AM")},
        {QStringLiteral("ASM"), QStringLiteral("AS")},
        {QStringLiteral("ATA"), QStringLiteral("AQ")},
        {QStringLiteral("ATF"), QStringLiteral("TF")},
        {QStringLiteral("ATG"), QStringLiteral("AG")},
        {QStringLiteral("AUS"), QStringLiteral("AU")},
        {QStringLiteral("AUT"), QStringLiteral("AT")},
        {QStringLiteral("AZE"), QStringLiteral("AZ")},
        {QStringLiteral("BDI"), QStringLiteral("BI")},
        {QStringLiteral("BEL"), QStringLiteral("BE")},
        {QStringLiteral("BEN"), QStringLiteral("BJ")},
        {QStringLiteral("BES"), QStringLiteral("BQ")},
        {QStringLiteral("BFA"), QStringLiteral("BF")},
        {QStringLiteral("BGD"), QStringLiteral("BD")},
        {QStringLiteral("BGR"), QStringLiteral("BG")},
        {QStringLiteral("BHR"), QStringLiteral("BH")},
        {QStringLiteral("BHS"), QStringLiteral("BS")},
        {QStringLiteral("BIH"), QStringLiteral("BA")},
        {QStringLiteral("BLM"), QStringLiteral("BL")},
        {QStringLiteral("BLR"), QStringLiteral("BY")},
        {QStringLiteral("BLZ"), QStringLiteral("BZ")},
        {QStringLiteral("BMU"), QStringLiteral("BM")},
        {QStringLiteral("BOL"), QStringLiteral("BO")},
        {QStringLiteral("BRA"), QStringLiteral("BR")},
        {QStringLiteral("BRB"), QStringLiteral("BB")},
        {QStringLiteral("BRN"), QStringLiteral("BN")},
        {QStringLiteral("BTN"), QStringLiteral("BT")},
        {QStringLiteral("BVT"), QStringLiteral("BV")},
        {QStringLiteral("BWA"), QStringLiteral("BW")},
        {QStringLiteral("CAF"), QStringLiteral("CF")},
        {QStringLiteral("CAN"), QStringLiteral("CA")},
        {QStringLiteral("CCK"), QStringLiteral("CC")},
        {QStringLiteral("CHE"), QStringLiteral("CH")},
        {QStringLiteral("CHL"), QStringLiteral("CL")},
        {QStringLiteral("CHN"), QStringLiteral("CN")},
        {QStringLiteral("CIV"), QStringLiteral("CI")},
        {QStringLiteral("CMR"), QStringLiteral("CM")},
        {QStringLiteral("COD"), QStringLiteral("CD")},
        {QStringLiteral("COG"), QStringLiteral("CG")},
        {QStringLiteral("COK"), QStringLiteral("CK")},
        {QStringLiteral("COL"), QStringLiteral("CO")},
        {QStringLiteral("COM"), QStringLiteral("KM")},
        {QStringLiteral("CPV"), QStringLiteral("CV")},
        {QStringLiteral("CRI"), QStringLiteral("CR")},
        {QStringLiteral("CUB"), QStringLiteral("CU")},
        {QStringLiteral("CUW"), QStringLiteral("CW")},
        {QStringLiteral("CXR"), QStringLiteral("CX")},
        {QStringLiteral("CYM"), QStringLiteral("KY")},
        {QStringLiteral("CYP"), QStringLiteral("CY")},
        {QStringLiteral("CZE"), QStringLiteral("CZ")},
        {QStringLiteral("DEU"), QStringLiteral("DE")},
        {QStringLiteral("DJI"), QStringLiteral("DJ")},
        {QStringLiteral("DMA"), QStringLiteral("DM")},
        {QStringLiteral("DNK"), QStringLiteral("DK")},
        {QStringLiteral("DOM"), QStringLiteral("DO")},
        {QStringLiteral("DZA"), QStringLiteral("DZ")},
        {QStringLiteral("ECU"), QStringLiteral("EC")},
        {QStringLiteral("EGY"), QStringLiteral("EG")},
        {QStringLiteral("ERI"), QStringLiteral("ER")},
        {QStringLiteral("ESH"), QStringLiteral("EH")},
        {QStringLiteral("ESP"), QStringLiteral("ES")},
        {QStringLiteral("EST"), QStringLiteral("EE")},
        {QStringLiteral("ETH"), QStringLiteral("ET")},
        {QStringLiteral("FIN"), QStringLiteral("FI")},
        {QStringLiteral("FJI"), QStringLiteral("FJ")},
        {QStringLiteral("FLK"), QStringLiteral("FK")},
        {QStringLiteral("FRA"), QStringLiteral("FR")},
        {QStringLiteral("FRO"), QStringLiteral("FO")},
        {QStringLiteral("FSM"), QStringLiteral("FM")},
        {QStringLiteral("GAB"), QStringLiteral("GA")},
        {QStringLiteral("GBR"), QStringLiteral("GB")},
        {QStringLiteral("GEO"), QStringLiteral("GE")},
        {QStringLiteral("GGY"), QStringLiteral("GG")},
        {QStringLiteral("GHA"), QStringLiteral("GH")},
        {QStringLiteral("GIB"), QStringLiteral("GI")},
        {QStringLiteral("GIN"), QStringLiteral("GN")},
        {QStringLiteral("GLP"), QStringLiteral("GP")},
        {QStringLiteral("GMB"), QStringLiteral("GM")},
        {QStringLiteral("GNB"), QStringLiteral("GW")},
        {QStringLiteral("GNQ"), QStringLiteral("GQ")},
        {QStringLiteral("GRC"), QStringLiteral("GR")},
        {QStringLiteral("GRD"), QStringLiteral("GD")},
        {QStringLiteral("GRL"), QStringLiteral("GL")},
        {QStringLiteral("GTM"), QStringLiteral("GT")},
        {QStringLiteral("GUF"), QStringLiteral("GF")},
        {QStringLiteral("GUM"), QStringLiteral("GU")},
        {QStringLiteral("GUY"), QStringLiteral("GY")},
        {QStringLiteral("HKG"), QStringLiteral("HK")},
        {QStringLiteral("HMD"), QStringLiteral("HM")},
        {QStringLiteral("HND"), QStringLiteral("HN")},
        {QStringLiteral("HRV"), QStringLiteral("HR")},
        {QStringLiteral("HTI"), QStringLiteral("HT")},
        {QStringLiteral("HUN"), QStringLiteral("HU")},
        {QStringLiteral("IDN"), QStringLiteral("ID")},
        {QStringLiteral("IMN"), QStringLiteral("IM")},
        {QStringLiteral("IND"), QStringLiteral("IN")},
        {QStringLiteral("IOT"), QStringLiteral("IO")},
        {QStringLiteral("IRL"), QStringLiteral("IE")},
        {QStringLiteral("IRN"), QStringLiteral("IR")},
        {QStringLiteral("IRQ"), QStringLiteral("IQ")},
        {QStringLiteral("ISL"), QStringLiteral("IS")},
        {QStringLiteral("ISR"), QStringLiteral("IL")},
        {QStringLiteral("ITA"), QStringLiteral("IT")},
        {QStringLiteral("JAM"), QStringLiteral("JM")},
        {QStringLiteral("JEY"), QStringLiteral("JE")},
        {QStringLiteral("JOR"), QStringLiteral("JO")},
        {QStringLiteral("JPN"), QStringLiteral("JP")},
        {QStringLiteral("KAZ"), QStringLiteral("KZ")},
        {QStringLiteral("KEN"), QStringLiteral("KE")},
        {QStringLiteral("KGZ"), QStringLiteral("KG")},
        {QStringLiteral("KHM"), QStringLiteral("KH")},
        {QStringLiteral("KIR"), QStringLiteral("KI")},
        {QStringLiteral("KNA"), QStringLiteral("KN")},
        {QStringLiteral("KOR"), QStringLiteral("KR")},
        {QStringLiteral("KWT"), QStringLiteral("KW")},
        {QStringLiteral("LAO"), QStringLiteral("LA")},
        {QStringLiteral("LBN"), QStringLiteral("LB")},
        {QStringLiteral("LBR"), QStringLiteral("LR")},
        {QStringLiteral("LBY"), QStringLiteral("LY")},
        {QStringLiteral("LCA"), QStringLiteral("LC")},
        {QStringLiteral("LIE"), QStringLiteral("LI")},
        {QStringLiteral("LKA"), QStringLiteral("LK")},
        {QStringLiteral("LSO"), QStringLiteral("LS")},
        {QStringLiteral("LTU"), QStringLiteral("LT")},
        {QStringLiteral("LUX"), QStringLiteral("LU")},
        {QStringLiteral("LVA"), QStringLiteral("LV")},
        {QStringLiteral("MAC"), QStringLiteral("MO")},
        {QStringLiteral("MAF"), QStringLiteral("MF")},
        {QStringLiteral("MAR"), QStringLiteral("MA")},
        {QStringLiteral("MCO"), QStringLiteral("MC")},
        {QStringLiteral("MDA"), QStringLiteral("MD")},
        {QStringLiteral("MDG"), QStringLiteral("MG")},
        {QStringLiteral("MDV"), QStringLiteral("MV")},
        {QStringLiteral("MEX"), QStringLiteral("MX")},
        {QStringLiteral("MHL"), QStringLiteral("MH")},
        {QStringLiteral("MKD"), QStringLiteral("MK")},
        {QStringLiteral("MLI"), QStringLiteral("ML")},
        {QStringLiteral("MLT"), QStringLiteral("MT")},
        {QStringLiteral("MMR"), QStringLiteral("MM")},
        {QStringLiteral("MNE"), QStringLiteral("ME")},
        {QStringLiteral("MNG"), QStringLiteral("MN")},
        {QStringLiteral("MNP"), QStringLiteral("MP")},
        {QStringLiteral("MOZ"), QStringLiteral("MZ")},
        {QStringLiteral("MRT"), QStringLiteral("MR")},
        {QStringLiteral("MSR"), QStringLiteral("MS")},
        {QStringLiteral("MTQ"), QStringLiteral("MQ")},
        {QStringLiteral("MUS"), QStringLiteral("MU")},
        {QStringLiteral("MWI"), QStringLiteral("MW")},
        {QStringLiteral("MYS"), QStringLiteral("MY")},
        {QStringLiteral("MYT"), QStringLiteral("YT")},
        {QStringLiteral("NAM"), QStringLiteral("NA")},
        {QStringLiteral("NCL"), QStringLiteral("NC")},
        {QStringLiteral("NER"), QStringLiteral("NE")},
        {QStringLiteral("NFK"), QStringLiteral("NF")},
        {QStringLiteral("NGA"), QStringLiteral("NG")},
        {QStringLiteral("NIC"), QStringLiteral("NI")},
        {QStringLiteral("NIU"), QStringLiteral("NU")},
        {QStringLiteral("NLD"), QStringLiteral("NL")},
        {QStringLiteral("NOR"), QStringLiteral("NO")},
        {QStringLiteral("NPL"), QStringLiteral("NP")},
        {QStringLiteral("NRU"), QStringLiteral("NR")},
        {QStringLiteral("NZL"), QStringLiteral("NZ")},
        {QStringLiteral("OMN"), QStringLiteral("OM")},
        {QStringLiteral("PAK"), QStringLiteral("PK")},
        {QStringLiteral("PAN"), QStringLiteral("PA")},
        {QStringLiteral("PCN"), QStringLiteral("PN")},
        {QStringLiteral("PER"), QStringLiteral("PE")},
        {QStringLiteral("PHL"), QStringLiteral("PH")},
        {QStringLiteral("PLW"), QStringLiteral("PW")},
        {QStringLiteral("PNG"), QStringLiteral("PG")},
        {QStringLiteral("POL"), QStringLiteral("PL")},
        {QStringLiteral("PRI"), QStringLiteral("PR")},
        {QStringLiteral("PRK"), QStringLiteral("KP")},
        {QStringLiteral("PRT"), QStringLiteral("PT")},
        {QStringLiteral("PRY"), QStringLiteral("PY")},
        {QStringLiteral("PSE"), QStringLiteral("PS")},
        {QStringLiteral("PYF"), QStringLiteral("PF")},
        {QStringLiteral("QAT"), QStringLiteral("QA")},
        {QStringLiteral("REU"), QStringLiteral("RE")},
        {QStringLiteral("ROU"), QStringLiteral("RO")},
        {QStringLiteral("RUS"), QStringLiteral("RU")},
        {QStringLiteral("RWA"), QStringLiteral("RW")},
        {QStringLiteral("SAU"), QStringLiteral("SA")},
        {QStringLiteral("SDN"), QStringLiteral("SD")},
        {QStringLiteral("SEN"), QStringLiteral("SN")},
        {QStringLiteral("SGP"), QStringLiteral("SG")},
        {QStringLiteral("SGS"), QStringLiteral("GS")},
        {QStringLiteral("SHN"), QStringLiteral("SH")},
        {QStringLiteral("SJM"), QStringLiteral("SJ")},
        {QStringLiteral("SLB"), QStringLiteral("SB")},
        {QStringLiteral("SLE"), QStringLiteral("SL")},
        {QStringLiteral("SLV"), QStringLiteral("SV")},
        {QStringLiteral("SMR"), QStringLiteral("SM")},
        {QStringLiteral("SOM"), QStringLiteral("SO")},
        {QStringLiteral("SPM"), QStringLiteral("PM")},
        {QStringLiteral("SRB"), QStringLiteral("RS")},
        {QStringLiteral("SSD"), QStringLiteral("SS")},
        {QStringLiteral("STP"), QStringLiteral("ST")},
        {QStringLiteral("SUR"), QStringLiteral("SR")},
        {QStringLiteral("SVK"), QStringLiteral("SK")},
        {QStringLiteral("SVN"), QStringLiteral("SI")},
        {QStringLiteral("SWE"), QStringLiteral("SE")},
        {QStringLiteral("SWZ"), QStringLiteral("SZ")},
        {QStringLiteral("SXM"), QStringLiteral("SX")},
        {QStringLiteral("SYC"), QStringLiteral("SC")},
        {QStringLiteral("SYR"), QStringLiteral("SY")},
        {QStringLiteral("TCA"), QStringLiteral("TC")},
        {QStringLiteral("TCD"), QStringLiteral("TD")},
        {QStringLiteral("TGO"), QStringLiteral("TG")},
        {QStringLiteral("THA"), QStringLiteral("TH")},
        {QStringLiteral("TJK"), QStringLiteral("TJ")},
        {QStringLiteral("TKL"), QStringLiteral("TK")},
        {QStringLiteral("TKM"), QStringLiteral("TM")},
        {QStringLiteral("TLS"), QStringLiteral("TL")},
        {QStringLiteral("TON"), QStringLiteral("TO")},
        {QStringLiteral("TTO"), QStringLiteral("TT")},
        {QStringLiteral("TUN"), QStringLiteral("TN")},
        {QStringLiteral("TUR"), QStringLiteral("TR")},
        {QStringLiteral("TUV"), QStringLiteral("TV")},
        {QStringLiteral("TWN"), QStringLiteral("TW")},
        {QStringLiteral("TZA"), QStringLiteral("TZ")},
        {QStringLiteral("UGA"), QStringLiteral("UG")},
        {QStringLiteral("UKR"), QStringLiteral("UA")},
        {QStringLiteral("UMI"), QStringLiteral("UM")},
        {QStringLiteral("URY"), QStringLiteral("UY")},
        {QStringLiteral("USA"), QStringLiteral("US")},
        {QStringLiteral("UZB"), QStringLiteral("UZ")},
        {QStringLiteral("VAT"), QStringLiteral("VA")},
        {QStringLiteral("VCT"), QStringLiteral("VC")},
        {QStringLiteral("VEN"), QStringLiteral("VE")},
        {QStringLiteral("VGB"), QStringLiteral("VG")},
        {QStringLiteral("VIR"), QStringLiteral("VI")},
        {QStringLiteral("VNM"), QStringLiteral("VN")},
        {QStringLiteral("VUT"), QStringLiteral("VU")},
        {QStringLiteral("WLF"), QStringLiteral("WF")},
        {QStringLiteral("WSM"), QStringLiteral("WS")},
        {QStringLiteral("YEM"), QStringLiteral("YE")},
        {QStringLiteral("ZAF"), QStringLiteral("ZA")},
        {QStringLiteral("ZMB"), QStringLiteral("ZM")},
        {QStringLiteral("ZWE"), QStringLiteral("ZW")}
      });

CountryUpdater::CountryUpdater(sql::SqlDatabase& sqlDb, const QString& timezoneFile, bool verboseParam)
  : db(sqlDb), verbose(verboseParam)
{
  if(atools::checkFile(Q_FUNC_INFO, timezoneFile))
  {
    timezone = new atools::timezone::TimeZoneManager();
    timezone->readFile(timezoneFile);
  }
}

CountryUpdater::~CountryUpdater()
{
  delete timezone;
}

QString CountryUpdater::updateAirportCountry(const QString& country, const atools::geo::Pos& pos)
{
  QString countryNew(country);

  if(!country.isEmpty())
  {
    // Country given
    const QString countryReplacement = countries.value(country.toUpper().simplified());

    if(!countryReplacement.isEmpty() && countryReplacement != country)
      // Found a replacement which is different - use this one
      countryNew = countryReplacement;
    else if((country.size() == 2 || country.size() == 3) && country.isUpper())
    {
      // A country code - lookup name
      QLocale::Territory territory = QLocale::codeToTerritory(country3To2.value(country.toUpper()));
      if(territory != QLocale::AnyTerritory)
        countryNew = QLocale::territoryToString(territory);
    }
  }
  else if(timezone != nullptr)
  {
    // No country given - look up in time zone database
    QTimeZone zone = timezone->getTimezone(pos);
    if(zone.isValid() && zone.territory() != QLocale::AnyTerritory)
      countryNew = QLocale::territoryToString(zone.territory());
  }

  if(countryNew == QStringLiteral("Default")) // From territoryToString()
    countryNew.clear();

  return atools::fs::util::capAdminName(countryNew);
}

} // namespace writer
} // namespace fs
} // namespace atools
