-- *****************************************************************************
-- Copyright 2015-2018 Alexander Barthel albar965@mailbox.org
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
-- ****************************************************************************/

-- Schema for the atools::fs::ap::AirportLoader class

drop table if exists airport;

-- Table for basic airport information extracted from runways.xml
-- file generated by the MakeRunways utility of Peter Dowson.
create table airport
(
  icao text collate nocase PRIMARY KEY,  -- Four of three letter ICAO code
  name text collate nocase,              -- Airport name
  city text collate nocase,
  state text collate nocase,             -- State, province or null if not available
  country text collate nocase,
  longitude real not null,               -- Airport center longitude in degrees
  latitude real not null,                -- Airport center latitude in degrees
  altitude integer not null,             -- Airport altitude in feet
  max_runway_length integer not null,    -- Maximum runway length in feet
  has_lights integer not null,           -- true if at least one runway has edge lighting
  has_ils integer not null               -- true if at least one runway has an ILS
);

